# Config file for Store2Hydro Project
# Goal: Realistic test of the hydro-to-PHS retrofit feature
# Higher investment cost, more clusters, myopic foresight
run:
  name: overnight_retrofit_test
  scenarios:
    enable: false
    file: ../config/rf_scenario_test.scenarios.yaml

scenario:
  clusters:
  - 10  # mehr Cluster → näher an einzelne Kraftwerke
  planning_horizons:
  - 2025
  - 2030
  - 2035

snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: left

foresight: overnight

sector:   # myopic only works for sector networks,
          # workaround: set all sectors to false
  transport: false
  heating: false #maybe set to true for heating as electricity sink
  biomass: false
  industry: false
  shipping: false
  aviation: false
  agriculture: false
  fossil_fuels: false
  hydrogen_underground_storage: false
  ammonia: false
  H2_network: false
  gas_network: false
  

clustering:
  temporal:
    resolution_elec: 3h
    resolution_sector: false
# problem with 24h cannot capture arbitrage potential

countries:
- ES

renewable:
  hydro: # defaults
    cutout: default
    carriers:
    - ror
    - PHS
    - hydro
    PHS_max_hours: 6
    hydro_max_hours: energy_capacity_totals_by_country
    flatten_dispatch: false
    flatten_dispatch_buffer: 0.2
    clip_min_inflow: 1.0
    eia_norm_year: false
    eia_correct_by_capacity: false
    eia_approximate_missing: false
### Retrofitting parameters:    
    retrofit_to_phs:
      enable: true
      capital_cost: 100  
      max_share: 0.5

# plotting parameters extension
plotting:
  balance_map: # hinzugefügt nach Fehlermeldung
    bus_carriers:
      - AC
  balance_map_interactive: # hinzugefügt nach Fehlermeldung
    bus_carriers:
      - AC 
  nice_names:
    retrofitted PHS: "Retrofitted Pumped Hydro Storage"
  tech_colors:
    retrofitted PHS: '#7ae8de'